command = /etc/profiles/per-user/sreysus/bin/nu
shell-integration = none
cursor-style = bar

theme = Catppuccin Frappe

window-padding-x = 30

font-size = 16
font-family = GeistMono Nerd Font Mono

macos-applescript = true

keybind = shift+enter=text:\n

# Free ⌘, for the macOS Quick Action.
keybind = super+,=unbind

keybind = global:ctrl+shift+backquote=toggle_quick_terminal
keybind = global:ctrl+alt+backquote=new_window

keybind = ctrl+shift+tab=previous_tab
keybind = ctrl+tab=next_tab

keybind = ctrl+j=goto_split:down
keybind = ctrl+k=goto_split:up
keybind = ctrl+h=goto_split:left
keybind = ctrl+l=goto_split:right

keybind = ctrl+shift+enter=toggle_split_zoom
keybind = cmd+shift+enter=unbind
